version: '3'

services:
  python3:
      image: sample-mlflow-python3
      container_name: sample-mlflow-python3
      user: 1000:1000
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
      working_dir: /app/data
      volumes:
        - /etc/passwd:/etc/passwd:ro
        - /etc/group:/etc/group:ro
        - ../data:/app/data
      ports:
        - 5000:5000
      tty: true
      command: mlflow server --backend-store-uri /app/data/mlflow/mlruns -h 0.0.0.0
