version: '3'

services:
  streamlit:
      image: sample_streamlit
      user: 1000:1000
      container_name: sample_streamlit
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
      working_dir: /app
      volumes:
        - /etc/passwd:/etc/passwd:ro
        - /etc/group:/etc/group:ro
        - ./app:/app
      ports:
        - 8501:8501
      tty: true
      command: streamlit run --server.runOnSave true ./app.py
