defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  run:
    dir: .hydra/${now:%Y-%m-%d}/${now:H%-%M-%S}
  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(asctime)s  [%(name)s][%(levelname)s]  %(message)s  %(filename)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}.log
    root:
      level: INFO
      handlers: [console, file]
    disable_existing_loggers: False
  sweep:
    dir: .hydra/multirun/${now:%Y-%m-%d}/${now:H%-%M-%S}
    subdir: trial_${hydra.job.num}
  sweeper:
    study_name: lgbm
    storage: null
    sampler:
      seed: 47
    n_trials: 10
    n_jobs: 1
    direction: maximize
    search_space:
      model.train_params.colsample_bytree:
        type: float
        low:  0.4
        high: 1.0
      model.train_params.learning_rate:
        type: float
        log: True
        low: 1e-2
        high: 1.0
      model.train_params.max_bin:
        type: int
        low: 100
        high: 400
      model.train_params.max_depth:
        type: int
        low: 3
        high: 21
      model.train_params.min_child_samples:
        type: int
        low: 0
        high: 25
      model.train_params.num_leaves:
        type: int
        low: 10
        high: 1000
      model.train_params.reg_alpha:
        type: float
        log: True
        low: 1e-4
        high: 0.1
      model.train_params.reg_lambda:
        type: float
        log: True
        low: 1e-4
        high: 0.1
      model.train_params.subsample_freq:
        type: int
        low: 0
        high: 10
      model.train_params.subsample:
        type: float
        low: 0.4
        high: 1.0


common:
  seed: 47
  fold: 5
  test_size: 0.3

mlflow:
  dir: data/mlflow
  experiment_name: LT用Train - Optuna
  tags:
    experiment_memo: LT用の使い捨て実験。あとで消します
    mlflow.user: cn47


data:
  train: data/01_raw/train.csv

model:
  callbacks:
    metric: average_precision
    early_stopping_rounds: 50
  train_params:
    # ---- fixed_params ----
    metric: average_precision
    force_col_wise: True
    boosting_type: gbdt
    importance_type: stplit
    is_unbalance: True
    min_child_weight: 1e-3
    min_split_gain: 0.0
    n_estimators: 1000
    n_jobs: -1
    objective: binary
    silent: True
    subsample_for_bin: 200000
    verbosity: -1
    # ---- search_params ----
    colsample_bytree: 1.0
    learning_rate: 0.1
    max_bin: 255
    max_depth: 15
    min_child_samples: 20
    num_leaves: 31
    reg_alpha: 1e-4
    reg_lambda: 1e-4
    subsample_freq: 0
    subsample: 1.0

metrics:
  - average_precision
  - roc_auc
  - accuracy
  - precision
  - recall
  - f1
